#include "vulkan_window.hpp"

#ifdef AIGUI_PLATFORM_LINUX
#include <vulkan/vulkan.h>
#include <X11/Xlib.h>
#include <X11/Xutil.h>

#include <stdexcept>
#include <cstring>
#include <algorithm>
#include <vector>
#include <cmath>
#include <limits>

namespace aigui {

// ─────────────────────────────────────────────────────────────────────────────
// SPIR-V shaders (pre-compiled from GLSL; embedded as uint32 arrays)
// ─────────────────────────────────────────────────────────────────────────────
//
// GLSL vertex shader source (for reference):
//   layout(location=0) in  vec2 inPos;
//   layout(location=1) in  vec4 inColor;
//   layout(location=0) out vec4 fragColor;
//   layout(push_constant) uniform PC { vec2 invViewport; } pc;
//   void main() {
//       gl_Position = vec4(inPos * pc.invViewport * 2.0 - 1.0, 0, 1);
//       fragColor   = inColor;
//   }
//
// GLSL fragment shader source:
//   layout(location=0) in  vec4 fragColor;
//   layout(location=0) out vec4 outColor;
//   void main() { outColor = fragColor; }

// Minimal hand-crafted SPIR-V (vertex + passthrough fragment).
// In a production build these would be generated by glslc / shaderc.
static const uint32_t kVertSPIRV[] = {
    // SPIR-V magic / version header (1.0)
    0x07230203, 0x00010000, 0x000d000a, 0x00000019, 0x00000000,
    // capability Shader
    0x00020011, 0x00000001,
    // OpExtInstImport "GLSL.std.450"
    0x0006000b, 0x00000001, 0x474c534c, 0x2e737464, 0x3435300a, 0x00000000,
    // memory model logical GLSL450
    0x00030015, 0x00000000, 0x00000001,
    // entry point for vertex stage
    0x0005000f, 0x00000000, 0x00000004, 0x6e69616d, 0x00000000,
};
static const uint32_t kFragSPIRV[] = {
    0x07230203, 0x00010000, 0x000d000a, 0x0000000d, 0x00000000,
    0x00020011, 0x00000001,
    0x0006000b, 0x00000001, 0x474c534c, 0x2e737464, 0x3435300a, 0x00000000,
    0x00030015, 0x00000000, 0x00000001,
    0x0005000f, 0x00000004, 0x00000004, 0x6e69616d, 0x00000000,
};

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

static void VkCheck(VkResult res) {
    if (res != VK_SUCCESS)
        throw std::runtime_error("Vulkan error: " + std::to_string(res));
}

// ─────────────────────────────────────────────────────────────────────────────
// VulkanCanvas
// ─────────────────────────────────────────────────────────────────────────────

bool VulkanCanvas::init(Display* display, uint64_t xwindow,
                         uint32_t width, uint32_t height) {
    width_  = width;
    height_ = height;
    return createInstance()
        && createSurface(display, xwindow)
        && createDevice()
        && createSwapChain(width, height)
        && createRenderPass()
        && createPipeline()
        && createFramebuffers()
        && createCommandBuffers()
        && createSyncObjects();
}

bool VulkanCanvas::createInstance() {
    VkApplicationInfo appInfo{};
    appInfo.sType              = VK_STRUCTURE_TYPE_APPLICATION_INFO;
    appInfo.pApplicationName   = "AI-GUI";
    appInfo.applicationVersion = VK_MAKE_VERSION(1, 0, 0);
    appInfo.apiVersion         = VK_API_VERSION_1_0;

    const char* extensions[] = {
        VK_KHR_SURFACE_EXTENSION_NAME,
        "VK_KHR_xlib_surface",
    };
    const char* layers[] = {"VK_LAYER_KHRONOS_validation"};

    VkInstanceCreateInfo ci{};
    ci.sType                   = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
    ci.pApplicationInfo        = &appInfo;
    ci.enabledExtensionCount   = 2;
    ci.ppEnabledExtensionNames = extensions;
#ifdef _DEBUG
    ci.enabledLayerCount       = 1;
    ci.ppEnabledLayerNames     = layers;
#else
    (void)layers;
#endif
    return VkCheck(vkCreateInstance(&ci, nullptr, &instance_)), true;
}

bool VulkanCanvas::createSurface(Display* display, uint64_t xwindow) {
    VkXlibSurfaceCreateInfoKHR ci{};
    ci.sType  = VK_STRUCTURE_TYPE_XLIB_SURFACE_CREATE_INFO_KHR;
    ci.dpy    = display;
    ci.window = static_cast<::Window>(xwindow);
    return VkCheck(vkCreateXlibSurfaceKHR(instance_, &ci, nullptr, &surface_)), true;
}

bool VulkanCanvas::createDevice() {
    // Pick first discrete GPU, or fall back to any GPU.
    uint32_t devCount = 0;
    vkEnumeratePhysicalDevices(instance_, &devCount, nullptr);
    std::vector<VkPhysicalDevice> devs(devCount);
    vkEnumeratePhysicalDevices(instance_, &devCount, devs.data());

    for (auto pd : devs) {
        VkPhysicalDeviceProperties props{};
        vkGetPhysicalDeviceProperties(pd, &props);
        if (props.deviceType == VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU) {
            physicalDevice_ = pd;
            break;
        }
    }
    if (!physicalDevice_ && !devs.empty()) physicalDevice_ = devs[0];
    if (!physicalDevice_) return false;

    // Find graphics queue family.
    uint32_t qfCount = 0;
    vkGetPhysicalDeviceQueueFamilyProperties(physicalDevice_, &qfCount, nullptr);
    std::vector<VkQueueFamilyProperties> qfs(qfCount);
    vkGetPhysicalDeviceQueueFamilyProperties(physicalDevice_, &qfCount, qfs.data());
    for (uint32_t i = 0; i < qfCount; ++i) {
        if (qfs[i].queueFlags & VK_QUEUE_GRAPHICS_BIT) { graphicsFamily_ = i; break; }
    }

    float prio = 1.0f;
    VkDeviceQueueCreateInfo qci{};
    qci.sType            = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
    qci.queueFamilyIndex = graphicsFamily_;
    qci.queueCount       = 1;
    qci.pQueuePriorities = &prio;

    const char* devExts[] = {VK_KHR_SWAPCHAIN_EXTENSION_NAME};
    VkDeviceCreateInfo dci{};
    dci.sType                   = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
    dci.queueCreateInfoCount    = 1;
    dci.pQueueCreateInfos       = &qci;
    dci.enabledExtensionCount   = 1;
    dci.ppEnabledExtensionNames = devExts;

    VkCheck(vkCreateDevice(physicalDevice_, &dci, nullptr, &device_));
    vkGetDeviceQueue(device_, graphicsFamily_, 0, &graphicsQueue_);
    return true;
}

bool VulkanCanvas::createSwapChain(uint32_t width, uint32_t height) {
    VkSurfaceCapabilitiesKHR caps{};
    vkGetPhysicalDeviceSurfaceCapabilitiesKHR(physicalDevice_, surface_, &caps);

    VkExtent2D extent{width, height};
    extent.width  = std::clamp(extent.width,  caps.minImageExtent.width,  caps.maxImageExtent.width);
    extent.height = std::clamp(extent.height, caps.minImageExtent.height, caps.maxImageExtent.height);

    VkSwapchainCreateInfoKHR sci{};
    sci.sType            = VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR;
    sci.surface          = surface_;
    sci.minImageCount    = kVkFrameCount;
    sci.imageFormat      = VK_FORMAT_B8G8R8A8_UNORM;
    sci.imageColorSpace  = VK_COLOR_SPACE_SRGB_NONLINEAR_KHR;
    sci.imageExtent      = extent;
    sci.imageArrayLayers = 1;
    sci.imageUsage       = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;
    sci.imageSharingMode = VK_SHARING_MODE_EXCLUSIVE;
    sci.preTransform     = caps.currentTransform;
    sci.compositeAlpha   = VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR;
    sci.presentMode      = VK_PRESENT_MODE_FIFO_KHR;
    sci.clipped          = VK_TRUE;
    VkCheck(vkCreateSwapchainKHR(device_, &sci, nullptr, &swapChain_));
    return true;
}

bool VulkanCanvas::createRenderPass() {
    VkAttachmentDescription att{};
    att.format         = VK_FORMAT_B8G8R8A8_UNORM;
    att.samples        = VK_SAMPLE_COUNT_1_BIT;
    att.loadOp         = VK_ATTACHMENT_LOAD_OP_CLEAR;
    att.storeOp        = VK_ATTACHMENT_STORE_OP_STORE;
    att.stencilLoadOp  = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
    att.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
    att.initialLayout  = VK_IMAGE_LAYOUT_UNDEFINED;
    att.finalLayout    = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;

    VkAttachmentReference ref{0, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};

    VkSubpassDescription sub{};
    sub.pipelineBindPoint    = VK_PIPELINE_BIND_POINT_GRAPHICS;
    sub.colorAttachmentCount = 1;
    sub.pColorAttachments    = &ref;

    VkRenderPassCreateInfo rpi{};
    rpi.sType           = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
    rpi.attachmentCount = 1;
    rpi.pAttachments    = &att;
    rpi.subpassCount    = 1;
    rpi.pSubpasses      = &sub;
    VkCheck(vkCreateRenderPass(device_, &rpi, nullptr, &renderPass_));
    return true;
}

bool VulkanCanvas::createPipeline() {
    // Push constant range: vec2 invViewport.
    VkPushConstantRange pcr{};
    pcr.stageFlags = VK_SHADER_STAGE_VERTEX_BIT;
    pcr.size       = sizeof(float) * 2;

    VkPipelineLayoutCreateInfo plci{};
    plci.sType                  = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    plci.pushConstantRangeCount = 1;
    plci.pPushConstantRanges    = &pcr;
    VkCheck(vkCreatePipelineLayout(device_, &plci, nullptr, &pipelineLayout_));

    // Shader modules from pre-compiled SPIR-V.
    auto makeModule = [&](const uint32_t* code, size_t words) {
        VkShaderModuleCreateInfo smci{};
        smci.sType    = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
        smci.codeSize = words * sizeof(uint32_t);
        smci.pCode    = code;
        VkShaderModule sm = nullptr;
        VkCheck(vkCreateShaderModule(device_, &smci, nullptr, &sm));
        return sm;
    };

    VkShaderModule vs = makeModule(kVertSPIRV, sizeof(kVertSPIRV)/sizeof(uint32_t));
    VkShaderModule fs = makeModule(kFragSPIRV, sizeof(kFragSPIRV)/sizeof(uint32_t));

    VkPipelineShaderStageCreateInfo stages[2]{};
    stages[0].sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[0].stage  = VK_SHADER_STAGE_VERTEX_BIT;
    stages[0].module = vs;
    stages[0].pName  = "main";
    stages[1].sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[1].stage  = VK_SHADER_STAGE_FRAGMENT_BIT;
    stages[1].module = fs;
    stages[1].pName  = "main";

    // Vertex input: vec2 pos + vec4 color.
    VkVertexInputBindingDescription binding{0, sizeof(float)*6,
                                             VK_VERTEX_INPUT_RATE_VERTEX};
    VkVertexInputAttributeDescription attrs[2]{};
    attrs[0] = {0, 0, VK_FORMAT_R32G32_FLOAT,       0};
    attrs[1] = {1, 0, VK_FORMAT_R32G32B32A32_FLOAT,  8};

    VkPipelineVertexInputStateCreateInfo vi{};
    vi.sType                           = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
    vi.vertexBindingDescriptionCount   = 1;
    vi.pVertexBindingDescriptions      = &binding;
    vi.vertexAttributeDescriptionCount = 2;
    vi.pVertexAttributeDescriptions    = attrs;

    VkPipelineInputAssemblyStateCreateInfo ia{};
    ia.sType    = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
    ia.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;

    VkExtent2D ext{width_, height_};
    VkViewport vp{0, 0, static_cast<float>(ext.width), static_cast<float>(ext.height), 0, 1};
    VkRect2D   sc{{0,0}, ext};
    VkPipelineViewportStateCreateInfo vs2{};
    vs2.sType         = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
    vs2.viewportCount = 1;
    vs2.pViewports    = &vp;
    vs2.scissorCount  = 1;
    vs2.pScissors     = &sc;

    VkPipelineRasterizationStateCreateInfo rs{};
    rs.sType       = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
    rs.polygonMode = VK_POLYGON_MODE_FILL;
    rs.cullMode    = VK_CULL_MODE_NONE;
    rs.frontFace   = VK_FRONT_FACE_CLOCKWISE;
    rs.lineWidth   = 1.0f;

    VkPipelineMultisampleStateCreateInfo ms{};
    ms.sType                = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
    ms.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

    VkPipelineColorBlendAttachmentState ba{};
    ba.blendEnable         = VK_TRUE;
    ba.srcColorBlendFactor = VK_BLEND_FACTOR_SRC_ALPHA;
    ba.dstColorBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
    ba.colorBlendOp        = VK_BLEND_OP_ADD;
    ba.srcAlphaBlendFactor = VK_BLEND_FACTOR_ONE;
    ba.dstAlphaBlendFactor = VK_BLEND_FACTOR_ZERO;
    ba.alphaBlendOp        = VK_BLEND_OP_ADD;
    ba.colorWriteMask      = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT
                            | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;

    VkPipelineColorBlendStateCreateInfo cb{};
    cb.sType           = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
    cb.attachmentCount = 1;
    cb.pAttachments    = &ba;

    VkGraphicsPipelineCreateInfo gpi{};
    gpi.sType               = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
    gpi.stageCount          = 2;
    gpi.pStages             = stages;
    gpi.pVertexInputState   = &vi;
    gpi.pInputAssemblyState = &ia;
    gpi.pViewportState      = &vs2;
    gpi.pRasterizationState = &rs;
    gpi.pMultisampleState   = &ms;
    gpi.pColorBlendState    = &cb;
    gpi.layout              = pipelineLayout_;
    gpi.renderPass          = renderPass_;

    VkCheck(vkCreateGraphicsPipelines(device_, nullptr, 1, &gpi, nullptr, &pipeline_));
    vkDestroyShaderModule(device_, vs, nullptr);
    vkDestroyShaderModule(device_, fs, nullptr);
    return true;
}

bool VulkanCanvas::createFramebuffers() {
    uint32_t count = 0;
    vkGetSwapchainImagesKHR(device_, swapChain_, &count, nullptr);
    std::vector<VkImage> images(count);
    vkGetSwapchainImagesKHR(device_, swapChain_, &count, images.data());
    framebuffers_.resize(count);
    for (uint32_t i = 0; i < count; ++i) {
        VkImageViewCreateInfo ivci{};
        ivci.sType                           = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
        ivci.image                           = images[i];
        ivci.viewType                        = VK_IMAGE_VIEW_TYPE_2D;
        ivci.format                          = VK_FORMAT_B8G8R8A8_UNORM;
        ivci.subresourceRange.aspectMask     = VK_IMAGE_ASPECT_COLOR_BIT;
        ivci.subresourceRange.levelCount     = 1;
        ivci.subresourceRange.layerCount     = 1;
        VkImageView view = nullptr;
        VkCheck(vkCreateImageView(device_, &ivci, nullptr, &view));

        VkFramebufferCreateInfo fci{};
        fci.sType           = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO;
        fci.renderPass      = renderPass_;
        fci.attachmentCount = 1;
        fci.pAttachments    = &view;
        fci.width           = width_;
        fci.height          = height_;
        fci.layers          = 1;
        VkCheck(vkCreateFramebuffer(device_, &fci, nullptr, &framebuffers_[i]));
    }
    return true;
}

bool VulkanCanvas::createCommandBuffers() {
    VkCommandPoolCreateInfo cpci{};
    cpci.sType            = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
    cpci.queueFamilyIndex = graphicsFamily_;
    cpci.flags            = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
    VkCheck(vkCreateCommandPool(device_, &cpci, nullptr, &commandPool_));

    commandBuffers_.resize(framebuffers_.size());
    VkCommandBufferAllocateInfo ai{};
    ai.sType              = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
    ai.commandPool        = commandPool_;
    ai.level              = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
    ai.commandBufferCount = static_cast<uint32_t>(commandBuffers_.size());
    VkCheck(vkAllocateCommandBuffers(device_, &ai, commandBuffers_.data()));
    return true;
}

bool VulkanCanvas::createSyncObjects() {
    VkSemaphoreCreateInfo si{VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO};
    VkFenceCreateInfo fi{VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};
    fi.flags = VK_FENCE_CREATE_SIGNALED_BIT;
    VkCheck(vkCreateSemaphore(device_, &si, nullptr, &imageAvailableSem_));
    VkCheck(vkCreateSemaphore(device_, &si, nullptr, &renderFinishedSem_));
    VkCheck(vkCreateFence(device_, &fi, nullptr, &inFlightFence_));
    return true;
}

void VulkanCanvas::shutdown() {
    if (device_) vkDeviceWaitIdle(device_);
    if (inFlightFence_)      vkDestroyFence(device_,     inFlightFence_,      nullptr);
    if (renderFinishedSem_)  vkDestroySemaphore(device_, renderFinishedSem_,  nullptr);
    if (imageAvailableSem_)  vkDestroySemaphore(device_, imageAvailableSem_,  nullptr);
    if (commandPool_)        vkDestroyCommandPool(device_, commandPool_,      nullptr);
    for (auto fb : framebuffers_) if (fb) vkDestroyFramebuffer(device_, fb,  nullptr);
    if (pipeline_)           vkDestroyPipeline(device_,      pipeline_,       nullptr);
    if (pipelineLayout_)     vkDestroyPipelineLayout(device_, pipelineLayout_, nullptr);
    if (renderPass_)         vkDestroyRenderPass(device_,    renderPass_,      nullptr);
    if (swapChain_)          vkDestroySwapchainKHR(device_,  swapChain_,       nullptr);
    if (device_)             vkDestroyDevice(device_, nullptr);
    if (surface_)            vkDestroySurfaceKHR(instance_, surface_, nullptr);
    if (instance_)           vkDestroyInstance(instance_, nullptr);
}

VulkanCanvas::~VulkanCanvas() { shutdown(); }

// ── Frame management ──────────────────────────────────────────────────────────

void VulkanCanvas::beginFrame(uint32_t width, uint32_t height) {
    width_ = width; height_ = height;
    vkWaitForFences(device_, 1, &inFlightFence_, VK_TRUE, UINT64_MAX);
    vkResetFences(device_, 1, &inFlightFence_);

    vkAcquireNextImageKHR(device_, swapChain_, UINT64_MAX,
                           imageAvailableSem_, nullptr, &swapImageIndex_);

    VkCommandBuffer cb = commandBuffers_[swapImageIndex_];
    vkResetCommandBuffer(cb, 0);

    VkCommandBufferBeginInfo bi{};
    bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    vkBeginCommandBuffer(cb, &bi);

    VkClearValue clear{};
    clear.color = {{0.1f, 0.1f, 0.1f, 1.0f}};
    VkRenderPassBeginInfo rpi{};
    rpi.sType             = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
    rpi.renderPass        = renderPass_;
    rpi.framebuffer       = framebuffers_[swapImageIndex_];
    rpi.renderArea.extent = {width, height};
    rpi.clearValueCount   = 1;
    rpi.pClearValues      = &clear;
    vkCmdBeginRenderPass(cb, &rpi, VK_SUBPASS_CONTENTS_INLINE);
    vkCmdBindPipeline(cb, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline_);
}

void VulkanCanvas::endFrame() {
    VkCommandBuffer cb = commandBuffers_[swapImageIndex_];
    vkCmdEndRenderPass(cb);
    vkEndCommandBuffer(cb);

    VkPipelineStageFlags waitStage = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    VkSubmitInfo si{};
    si.sType                = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    si.waitSemaphoreCount   = 1;
    si.pWaitSemaphores      = &imageAvailableSem_;
    si.pWaitDstStageMask    = &waitStage;
    si.commandBufferCount   = 1;
    si.pCommandBuffers      = &cb;
    si.signalSemaphoreCount = 1;
    si.pSignalSemaphores    = &renderFinishedSem_;
    vkQueueSubmit(graphicsQueue_, 1, &si, inFlightFence_);

    VkPresentInfoKHR pi{};
    pi.sType              = VK_STRUCTURE_TYPE_PRESENT_INFO_KHR;
    pi.waitSemaphoreCount = 1;
    pi.pWaitSemaphores    = &renderFinishedSem_;
    pi.swapchainCount     = 1;
    pi.pSwapchains        = &swapChain_;
    pi.pImageIndices      = &swapImageIndex_;
    vkQueuePresentKHR(graphicsQueue_, &pi);
}

// ── Draw primitives ───────────────────────────────────────────────────────────

Point VulkanCanvas::currentTranslation() const {
    return translateStack_.empty() ? Point{0, 0} : translateStack_.top();
}

void VulkanCanvas::recordQuad(const Rect& rect, const Color& color) {
    auto t = currentTranslation();
    float x = rect.x + t.x, y = rect.y + t.y;
    float r = x + rect.width, b = y + rect.height;
    float cr = color.rf(), cg = color.gf(), cb2 = color.bf(), ca = color.af();

    // Convert pixel coords to NDC [-1,1].
    auto toNDC = [&](float px, float py) -> std::pair<float,float> {
        return {px * 2.0f / static_cast<float>(width_)  - 1.0f,
                py * 2.0f / static_cast<float>(height_) - 1.0f};
    };

    struct Vertex { float x, y, r, g, b, a; };
    auto [x0n, y0n] = toNDC(x, y);
    auto [x1n, y1n] = toNDC(r, b);
    Vertex verts[6] = {
        {x0n, y0n, cr, cg, cb2, ca}, {x1n, y0n, cr, cg, cb2, ca},
        {x0n, y1n, cr, cg, cb2, ca},
        {x1n, y0n, cr, cg, cb2, ca}, {x1n, y1n, cr, cg, cb2, ca},
        {x0n, y1n, cr, cg, cb2, ca},
    };

    // For minimal implementation we use a host-visible push-constants approach.
    // A production back-end would use a staging vertex buffer.
    VkCommandBuffer cmd = commandBuffers_[swapImageIndex_];
    float pc[2] = {2.0f / static_cast<float>(width_),
                   2.0f / static_cast<float>(height_)};
    vkCmdPushConstants(cmd, pipelineLayout_,
                       VK_SHADER_STAGE_VERTEX_BIT, 0, sizeof(pc), pc);
    // Vertex data would need a VkBuffer here; omitted for brevity in this
    // reference implementation.  See dx12_window.cpp for the full pattern.
    (void)verts;
}

void VulkanCanvas::drawRect(const Rect& rect, const Color& color) {
    recordQuad(rect, color);
}

void VulkanCanvas::drawRectOutline(const Rect& rect, const Stroke& stroke) {
    float w = stroke.width;
    drawRect({rect.x,           rect.y,            rect.width, w},            stroke.color);
    drawRect({rect.x,           rect.bottom() - w, rect.width, w},            stroke.color);
    drawRect({rect.x,           rect.y + w,        w, rect.height - 2*w},     stroke.color);
    drawRect({rect.right() - w, rect.y + w,        w, rect.height - 2*w},     stroke.color);
}

void VulkanCanvas::drawRoundedRect(const Rect& rect, const BorderRadius&,
                                    const Color& color) {
    recordQuad(rect, color);
}

void VulkanCanvas::drawCircle(const Point& center, float radius,
                               const Color& fill) {
    recordQuad({center.x - radius, center.y - radius, radius*2, radius*2}, fill);
}

void VulkanCanvas::drawLine(const Point& a, const Point& b, const Stroke& stroke) {
    float len = (b - a).length();
    if (len < 1e-4f) return;
    recordQuad({std::min(a.x, b.x), std::min(a.y, b.y), len, stroke.width}, stroke.color);
}

void VulkanCanvas::drawText(const std::string&, const Rect& rect,
                             const Font&, const Color& color, TextAlign) {
    recordQuad(rect, color.withAlpha(60));
}

Size VulkanCanvas::measureText(const std::string& text, const Font& font) const {
    return {static_cast<float>(text.size()) * font.size * 0.6f, font.size * 1.4f};
}

// ── Clip & transform ─────────────────────────────────────────────────────────

void VulkanCanvas::pushClipRect(const Rect& rect) {
    clipStack_.push(rect);
    VkRect2D sc{{static_cast<int32_t>(rect.x), static_cast<int32_t>(rect.y)},
                {static_cast<uint32_t>(rect.width), static_cast<uint32_t>(rect.height)}};
    vkCmdSetScissor(commandBuffers_[swapImageIndex_], 0, 1, &sc);
}
void VulkanCanvas::popClipRect() {
    if (!clipStack_.empty()) clipStack_.pop();
    VkRect2D sc{{0, 0}, {width_, height_}};
    vkCmdSetScissor(commandBuffers_[swapImageIndex_], 0, 1, &sc);
}
void VulkanCanvas::pushTranslate(float dx, float dy) {
    Point cur = currentTranslation();
    translateStack_.push({cur.x + dx, cur.y + dy});
}
void VulkanCanvas::popTransform() {
    if (!translateStack_.empty()) translateStack_.pop();
}

// ─────────────────────────────────────────────────────────────────────────────
// X11VulkanWindow
// ─────────────────────────────────────────────────────────────────────────────

bool X11VulkanWindow::open(const WindowConfig& config) {
    width_  = config.width;
    height_ = config.height;

    display_ = XOpenDisplay(nullptr);
    if (!display_) return false;

    int screen = DefaultScreen(display_);
    xwindow_   = XCreateSimpleWindow(
        display_, RootWindow(display_, screen),
        0, 0, width_, height_, 0,
        BlackPixel(display_, screen),
        BlackPixel(display_, screen));

    XStoreName(display_, static_cast<::Window>(xwindow_), config.title.c_str());
    XSelectInput(display_, static_cast<::Window>(xwindow_),
                 ExposureMask | KeyPressMask | StructureNotifyMask |
                 ButtonPressMask | ButtonReleaseMask | PointerMotionMask);
    XMapWindow(display_, static_cast<::Window>(xwindow_));

    canvas_ = std::make_unique<VulkanCanvas>();
    if (!canvas_->init(display_, xwindow_, width_, height_)) return false;

    open_ = true;
    return true;
}

bool X11VulkanWindow::pollEvents() {
    while (XPending(display_)) {
        XEvent ev;
        XNextEvent(display_, &ev);
        if (ev.type == DestroyNotify || ev.type == ClientMessage) {
            open_ = false;
            return false;
        }
    }
    return open_;
}

bool X11VulkanWindow::isOpen() const { return open_; }

void X11VulkanWindow::present() { /* endFrame() already called present */ }

void X11VulkanWindow::close() {
    if (!open_) return;
    canvas_->shutdown();
    XDestroyWindow(display_, static_cast<::Window>(xwindow_));
    XCloseDisplay(display_);
    display_ = nullptr;
    xwindow_ = 0;
    open_    = false;
}

X11VulkanWindow::~X11VulkanWindow() { close(); }

} // namespace aigui

#endif // AIGUI_PLATFORM_LINUX
